name: Test bpf_conformance and publish results

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - ubuntu-2204
    container: 
      image: "manjusakalza/bpftime-base-image:${{matrix.container}}"
      options: --privileged
    steps:

    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies
    
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: actions/setup-python@v4
      if: startsWith(matrix.container,'ubuntu')
      with:
        python-version: '3.8'

    - name: build
      run: 
           |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBPFTIME_ENABLE_UNIT_TESTING=1
          cmake --build build --target all -j

    - name: get bpf_conformance
      run: |
        git clone https://github.com/Alan-Jowett/bpf_conformance --recursive
        cd bpf_conformance
        cmake . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --target bpf_conformance_runner

    - name: test bpf_conformance
      run: |
        cd bpf_conformance
        ./build/bin/bpf_conformance_runner  --test_file_directory \
        tests --plugin_path \
        ../build/test/bpf_conformance_runner/bpftime_vm_bpf_conformance_runner \
        > ../bpf_conformance_results.txt  || echo "ok"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: '.'
  deploy:
    if: github.event_name == 'push'
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action


